// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type RewardReq struct {
	Id 		int64  `json:"id,optional"`
	Biz   string `json:"biz"`
	ResourceId string `json:""`
	Amt     int64 `json:""`
	Platform string `json:""`
}

type RewardResp struct {
	PayUrl string `json:"pay_url"`
}



