// Code generated by goctl. DO NOT EDIT.
// Source: sms.proto

package api

import (
	"codexie.com/w-book-code/api/pb"
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResult   = pb.CommonResult
	SendCodeReq    = pb.SendCodeReq
	SendCodeResp   = pb.SendCodeResp
	VerifyCodeReq  = pb.VerifyCodeReq
	VerifyCodeResp = pb.VerifyCodeResp

	CodeClient interface {
		SendCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*SendCodeResp, error)
		VerifyCode(ctx context.Context, in *VerifyCodeReq, opts ...grpc.CallOption) (*VerifyCodeResp, error)
	}

	defaultSMS struct {
		cli zrpc.Client
	}
)

func NewCodeClient(cli zrpc.Client) CodeClient {
	return &defaultSMS{
		cli: cli,
	}
}

func (m *defaultSMS) SendCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*SendCodeResp, error) {
	client := pb.NewCodeClient(m.cli.Conn())
	return client.SendCode(ctx, in, opts...)
}

func (m *defaultSMS) VerifyCode(ctx context.Context, in *VerifyCodeReq, opts ...grpc.CallOption) (*VerifyCodeResp, error) {
	client := pb.NewCodeClient(m.cli.Conn())
	return client.VerifyCode(ctx, in, opts...)
}
