// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"


	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, handler *AliPayHandler) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/pay/ali/callback",
				Handler: handler.Callback,
			},
		},
	)
}
