// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"codexie.com/w-book-common/ioc"
	"codexie.com/w-book-common/kafka/producer"
	"codexie.com/w-book-payment/internal/config"
	"codexie.com/w-book-payment/internal/handler"
	"codexie.com/w-book-payment/internal/logic"
	"codexie.com/w-book-payment/internal/repo"
	"codexie.com/w-book-payment/internal/svc"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewPaymentApp(config2 config.Config) (*App, error) {
	aliPayConfig := config.GetAliPayConfig(config2)
	mySQLConf := config.GetMySQLConf(config2)
	db := ioc.InitGormDB(mySQLConf)
	paymentRepository := repo.NewPaymentRepository(db)
	payMsgRepo := repo.NewPayMsgRepo(db)
	paymentLogic := logic.NewPaymentLogic(paymentRepository, payMsgRepo)
	kafkaConf := config.GetKafkaConf(config2)
	client := ioc.InitKafkaClient(kafkaConf)
	producerProducer := producer.NewKafkaProducer(client)
	aliPayLogic := logic.NewAliPayLogic(aliPayConfig, paymentLogic, producerProducer)
	serviceContext := svc.NewServiceContext(config2, aliPayLogic)
	aliPayHandler := handler.NewAliPayHandler(serviceContext, aliPayLogic)
	redisConf := config.GetRedisConf(config2)
	redisClient := ioc.InitRedis(redisConf)
	server := InitServer(config2, aliPayHandler, redisClient)
	paymentServer := InitRpcServer(serviceContext)
	payStatusJob := InitPayStatusJob(serviceContext, paymentRepository)
	jobCron := InitJobCron(payStatusJob, redisClient)
	app := &App{
		Server:    server,
		RpcServer: paymentServer,
		SvcCtx:    serviceContext,
		JobCron:   jobCron,
	}
	return app, nil
}

// wire.go:

var AppSet = wire.NewSet(InitServer, InitRpcServer, InitJobCron)

var HandlerSet = wire.NewSet(handler.NewAliPayHandler)

var LogicSet = wire.NewSet(logic.NewAliPayLogic, logic.NewPaymentLogic)

var SvcSet = wire.NewSet(svc.NewServiceContext)

var RepoSet = wire.NewSet(repo.NewPaymentRepository, repo.NewPayMsgRepo)

var DbSet = wire.NewSet(ioc.InitGormDB, ioc.InitRedis)

var JobSet = wire.NewSet(InitPayStatusJob)

var ConfSet = wire.NewSet(config.GetAliPayConfig, config.GetMySQLConf, config.GetRedisConf, config.GetKafkaConf)

var MessageSet = wire.NewSet(ioc.InitKafkaClient, producer.NewKafkaProducer)
