// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"codexie.com/w-book-user/internal/config"

	"github.com/zeromicro/go-zero/rest"
)


func RegisterHandlers(server *rest.Server, c config.Config, userHandler *UserHandler) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: userHandler.LoginHandler,
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/refresh",
				Handler: userHandler.RefreshHandler,
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/sign",
				Handler: userHandler.SignHandler,
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login_sms",
				Handler: userHandler.SmsLoginHandler,
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login_sms/code",
				Handler: userHandler.SendLoginCodeHandler,
			},
		},
		rest.WithPrefix("/v1"),
		rest.WithMaxBytes(1048576),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/profile",
				Handler: userHandler.ProfileHandler,
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/edit",
				Handler: userHandler.EditHandler,
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/logout",
				Handler: userHandler.LogoutHandler,
			},
		},

		rest.WithPrefix("/v1"),
		rest.WithMaxBytes(1048576),
	)
	
}



