// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

import "codexie.com/w-book-interact/internal/domain"

type LikeResourceReq struct {
	Biz        string `json:"biz"`
	BizId      int64  `json:"biz_id"`
	Liked      uint8  `json:"liked"`
}

type CollectionReq struct {
	Id        int64 `json:"id,optional"`
	Name        string `json:"name"`
	Action      uint8  `json:"action"`
	
}

type CollectResourceReq struct {
	Id        int64 `json:"id,optional"`
	Biz        string `json:"biz"`
	BizId      int64  `json:"biz_id"`
	Cid      int64  `json:"cid"`
	Action      uint8  `json:"action"`
}

func (req *CollectResourceReq) ToDomain(uid int64) *domain.CollectionItem {
	return &domain.CollectionItem{
		Id: req.Id,
		Uid: uid,
		Biz: req.Biz,
		BizId: req.BizId,
		Cid: req.Cid,
		Action: req.Action,
	}
}

type EditArticleResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type ArticlePageReq struct {
	Page   int `form:"page"`
	Size   int `form:"size"`
}

type ArticleViewReq struct {
	Id    int64 `form:"id"`
	IsPublished bool `form:isPublished`
}
