// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type LikeResourceReq struct {
	Biz        string `json:"biz"`
	BizId      int64  `json:"biz_id"`
	Liked      uint8  `json:"liked"`
}

type EditArticleResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type ArticlePageReq struct {
	Page   int `form:"page"`
	Size   int `form:"size"`
}

type ArticleViewReq struct {
	Id    int64 `form:"id"`
	IsPublished bool `form:isPublished`
}
