// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"codexie.com/w-book-common/ioc"
	"codexie.com/w-book-common/kafka/producer"
	"codexie.com/w-book-common/repo"
	"codexie.com/w-book-interact/internal/config"
	"codexie.com/w-book-interact/internal/dao/cache"
	"codexie.com/w-book-interact/internal/event"
	"codexie.com/w-book-interact/internal/handler"
	"codexie.com/w-book-interact/internal/logic"
	repo2 "codexie.com/w-book-interact/internal/repo"
	"codexie.com/w-book-interact/internal/server"
	"codexie.com/w-book-interact/internal/svc"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewInteractApp(config2 config.Config, mysqlConf ioc.MySQLConf, redisConf ioc.RedisConf, kafkaConf ioc.KafkaConf) (*App, error) {
	serviceContext := svc.NewServiceContext(config2)
	client := ioc.InitRedis(redisConf)
	redsync := ioc.InitRedLock(redisConf)
	interactCache := cache.NewInteractRedis(client, redsync)
	db := ioc.InitGormDB(mysqlConf)
	baseRepo := repo.NewBaseRepo(db)
	iLikeInfoRepository := repo2.NewLikeInfoRepository(interactCache, baseRepo)
	topLikeCache := cache.NewBigCacheResourceCache()
	iInteractRepo := repo2.NewInteractRepository(baseRepo, interactCache, topLikeCache)
	iCollectRepository := repo2.NewCollectRepository(interactCache, baseRepo)
	interactLogic := logic.NewInteractLogic(iLikeInfoRepository, iInteractRepo, iCollectRepository)
	interactHandler := handler.NewInteractHandler(serviceContext, interactLogic)
	maintainceHandler := handler.NewMaintainceHandler(baseRepo)
	server := InitServer(config2, interactHandler, maintainceHandler, client)
	saramaClient := ioc.InitKafkaClient(kafkaConf)
	readEvtListener := event.NewBatchReadEventListener(saramaClient, iInteractRepo)
	createEventListener := event.NewCreateEventListener(saramaClient, iInteractRepo)
	v := InitConsumers(readEvtListener, createEventListener)
	commentCache := cache.NewCommentRedisCache(client)
	iCommentRepo := repo2.NewCommentRepo(db, commentCache)
	producerProducer := producer.NewKafkaProducer(saramaClient)
	commentLogic := logic.NewCommentLogic(iCommentRepo, producerProducer)
	commentJob := InitCommentJob(commentLogic, commentCache)
	jobCron := InitJobCron(commentJob, client)
	app := &App{
		Server:    server,
		Consumers: v,
		JobCron:   jobCron,
	}
	return app, nil
}

func NewRpcApp(c config.Config, mysqlConf ioc.MySQLConf, redisConf ioc.RedisConf, kafkaConf ioc.KafkaConf) (*server.InteractionServer, error) {
	serviceContext := svc.NewServiceContext(c)
	client := ioc.InitRedis(redisConf)
	redsync := ioc.InitRedLock(redisConf)
	interactCache := cache.NewInteractRedis(client, redsync)
	db := ioc.InitGormDB(mysqlConf)
	baseRepo := repo.NewBaseRepo(db)
	iLikeInfoRepository := repo2.NewLikeInfoRepository(interactCache, baseRepo)
	topLikeCache := cache.NewBigCacheResourceCache()
	iInteractRepo := repo2.NewInteractRepository(baseRepo, interactCache, topLikeCache)
	iCollectRepository := repo2.NewCollectRepository(interactCache, baseRepo)
	interactLogic := logic.NewInteractLogic(iLikeInfoRepository, iInteractRepo, iCollectRepository)
	commentCache := cache.NewCommentRedisCache(client)
	iCommentRepo := repo2.NewCommentRepo(db, commentCache)
	saramaClient := ioc.InitKafkaClient(kafkaConf)
	producerProducer := producer.NewKafkaProducer(saramaClient)
	commentLogic := logic.NewCommentLogic(iCommentRepo, producerProducer)
	interactionServer := InitRpcServer(serviceContext, interactLogic, commentLogic)
	return interactionServer, nil
}

// wire.go:

var ServerSet = wire.NewSet(InitServer, InitRpcServer)

var HandlerSet = wire.NewSet(handler.NewInteractHandler, handler.NewMaintainceHandler)

var LogicSet = wire.NewSet(logic.NewInteractLogic, logic.NewCommentLogic)

var SvcSet = wire.NewSet(svc.NewServiceContext)

var RepoSet = wire.NewSet(repo2.NewCollectRepository, repo2.NewInteractRepository, repo2.NewLikeInfoRepository, repo.NewBaseRepo, repo2.NewCommentRepo)

var DaoSet = wire.NewSet(cache.NewInteractRedis, cache.NewBigCacheResourceCache, cache.NewCommentRedisCache)

var DbSet = wire.NewSet(ioc.InitGormDB, ioc.InitRedis, ioc.InitRedLock)

var MessageSet = wire.NewSet(ioc.InitKafkaClient, producer.NewKafkaProducer)

var ListenerSet = wire.NewSet(InitConsumers, event.NewCreateEventListener, event.NewBatchReadEventListener, event.NewCommentEvtListener)

var WokerSet = wire.NewSet(InitCommentJob, InitJobCron)
