// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.1
// source: user.proto

package trace

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TraceServer_GetUser_FullMethodName = "/trace.TraceServer/GetUser"
)

// TraceServerClient is the client API for TraceServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义 UserService 服务
type TraceServerClient interface {
	// 定义 GetUser 方法
	GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
}

type traceServerClient struct {
	cc grpc.ClientConnInterface
}

func NewTraceServerClient(cc grpc.ClientConnInterface) TraceServerClient {
	return &traceServerClient{cc}
}

func (c *traceServerClient) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResp)
	err := c.cc.Invoke(ctx, TraceServer_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TraceServerServer is the server API for TraceServer service.
// All implementations must embed UnimplementedTraceServerServer
// for forward compatibility.
//
// 定义 UserService 服务
type TraceServerServer interface {
	// 定义 GetUser 方法
	GetUser(context.Context, *GetUserReq) (*GetUserResp, error)
	mustEmbedUnimplementedTraceServerServer()
}

// UnimplementedTraceServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTraceServerServer struct{}

func (UnimplementedTraceServerServer) GetUser(context.Context, *GetUserReq) (*GetUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedTraceServerServer) mustEmbedUnimplementedTraceServerServer() {}
func (UnimplementedTraceServerServer) testEmbeddedByValue()                     {}

// UnsafeTraceServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TraceServerServer will
// result in compilation errors.
type UnsafeTraceServerServer interface {
	mustEmbedUnimplementedTraceServerServer()
}

func RegisterTraceServerServer(s grpc.ServiceRegistrar, srv TraceServerServer) {
	// If the following call pancis, it indicates UnimplementedTraceServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TraceServer_ServiceDesc, srv)
}

func _TraceServer_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraceServerServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TraceServer_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraceServerServer).GetUser(ctx, req.(*GetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TraceServer_ServiceDesc is the grpc.ServiceDesc for TraceServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TraceServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trace.TraceServer",
	HandlerType: (*TraceServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _TraceServer_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
