// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"codexie.com/w-book-common/ioc"
	"codexie.com/w-book-reward/internal/config"
	"codexie.com/w-book-reward/internal/handler"
	"codexie.com/w-book-reward/internal/logic"
	"codexie.com/w-book-reward/internal/repo"
	"codexie.com/w-book-reward/internal/svc"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewApp(config2 config.Config) (*App, error) {
	serviceContext := svc.NewServiceContext(config2)
	mySQLConf := config.GetMySQLConf(config2)
	db := ioc.InitGormDB(mySQLConf)
	rewardRepository := repo.NewRewardRepository(db)
	rpcClientConf := config.GetPaymentRpcConf(config2)
	paymentClient := InitPaymentRpcClient(rpcClientConf)
	rewardLogic := logic.NewRewardLogic(rewardRepository, paymentClient)
	rewardHandler := handler.NewRewardHandler(serviceContext, rewardLogic)
	redisConf := config.GetRedisConf(config2)
	client := ioc.InitRedis(redisConf)
	server := InitServer(config2, rewardHandler, client)
	app := &App{
		Server: server,
	}
	return app, nil
}

// wire.go:

var ServerSet = wire.NewSet(InitServer)

var HandlerSet = wire.NewSet(handler.NewRewardHandler)

var LogicSet = wire.NewSet(logic.NewRewardLogic)

var SvcSet = wire.NewSet(svc.NewServiceContext)

var RepoSet = wire.NewSet(repo.NewRewardRepository)

var DbSet = wire.NewSet(ioc.InitGormDB, ioc.InitRedis, ioc.InitRedLock)

var RpcSet = wire.NewSet(InitPaymentRpcClient)

var ConfSet = wire.NewSet(config.GetKafkaConf, config.GetMySQLConf, config.GetPaymentRpcConf, config.GetRedisConf)
