services:
  mysql8:
    container_name: "mysql-integration"
    image: mysql:8.0.29
    command: --default_authentication_plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    # 设置初始化脚本
      - ./scripts/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  
    ports:
      # 映射 13316端口
      - "13306:3306"
    networks:
      default:
  redis:
    container_name: "redis-integration"
    image: 'redis:7.2.4-alpine'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '16379:6379'
    networks:
      default:
  kafka:
    container_name: "kafka-integration"
    image: 'bitnami/kafka:3.6.0'
    ports:
      - '19092:9092'
      - '19094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:19094,EXTERNAL://localhost:19094  #通知给client的访问地址
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      default:
