// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"codexie.com/w-book-user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/sign",
				Handler: SignHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
		rest.WithMaxBytes(1048576),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/profile",
				Handler: ProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/edit",
				Handler: EditHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
		rest.WithMaxBytes(1048576),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
