// Code generated by goctl. DO NOT EDIT.
package types

type AliPayCallResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type AliPaymentMsg struct {
	NotifyType          string `json:"notify_type,optional"`
	NotifyID            string `json:"notify_id,optional"`
	NotifyTime          string `json:"notify_time,optional"`
	SignType            string `json:"sign_type,optional"`
	Sign                string `json:"sign,optional"`
	MerchantAppID       string `json:"merchant_app_id,optional"`
	BuyerOpenID         string `json:"buyer_open_id,optional"`
	FundBillList        string `json:"fund_bill_list,optional"`
	ReceiptAmount       string `json:"receipt_amount,optional"`
	InvoiceAmount       string `json:"invoice_amount,optional"`
	BuyerPayAmount      string `json:"buyer_pay_amount,optional"`
	PointAmount         string `json:"point_amount,optional"`
	VoucherDetailList   string `json:"voucher_detail_list,optional"`
	PassbackParams      string `json:"passback_params,optional"`
	OutChannelType      string `json:"out_channel_type,optional"`
	TradeNo             string `json:"trade_no,optional"`
	AppID               string `json:"app_id,optional"`
	OutTradeNo          string `json:"out_trade_no,optional"`
	OutBizNo            string `json:"out_biz_no,optional"`
	BuyerID             string `json:"buyer_id,optional"`
	SellerID            string `json:"seller_id,optional"`
	TradeStatus         string `json:"trade_status,optional"`
	TotalAmount         string `json:"total_amount,optional"`
	RefundFee           string `json:"refund_fee,optional"`
	Subject             string `json:"subject,optional"`
	Body                string `json:"body,optional"`
	GmtCreate           string `json:"gmt_create,optional"`
	GmtPayment          string `json:"gmt_payment,optional"`
	GmtRefund           string `json:"gmt_refund,optional"`
	GmtClose            string `json:"gmt_close,optional"`
	BuyerLogonID        string `json:"buyer_logon_id,optional"`
	ChargeAmount        string `json:"charge_amount,optional"`
	ChargeFlags         string `json:"charge_flags,optional"`
	SettlementID        string `json:"settlement_id,optional"`
	ReceiptCurrencyType string `json:"receipt_currency_type,optional"`
	HybAmount           string `json:"hyb_amount,optional"`
	EnterprisePayInfo   string `json:"enterprise_pay_info,optional"`
}
