// Code generated by goctl. DO NOT EDIT.
package types

type AliPayCallResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type AliPaymentMsg struct {
	NotifyType          string `json:"notify_type"`
	NotifyID            string `json:"notify_id"`
	NotifyTime          string `json:"notify_time"`
	SignType            string `json:"sign_type"`
	Sign                string `json:"sign"`
	MerchantAppID       string `json:"merchant_app_id"`
	BuyerOpenID         string `json:"buyer_open_id"`
	FundBillList        string `json:"fund_bill_list"`
	ReceiptAmount       string `json:"receipt_amount"`
	InvoiceAmount       string `json:"invoice_amount"`
	BuyerPayAmount      string `json:"buyer_pay_amount"`
	PointAmount         string `json:"point_amount"`
	VoucherDetailList   string `json:"voucher_detail_list"`
	PassbackParams      string `json:"passback_params"`
	OutChannelType      string `json:"out_channel_type"`
	TradeNo             string `json:"trade_no"`
	AppID               string `json:"app_id"`
	OutTradeNo          string `json:"out_trade_no"`
	OutBizNo            string `json:"out_biz_no"`
	BuyerID             string `json:"buyer_id"`
	SellerID            string `json:"seller_id"`
	TradeStatus         string `json:"trade_status"`
	TotalAmount         string `json:"total_amount"`
	RefundFee           string `json:"refund_fee"`
	Subject             string `json:"subject"`
	Body                string `json:"body"`
	GmtCreate           string `json:"gmt_create"`
	GmtPayment          string `json:"gmt_payment"`
	GmtRefund           string `json:"gmt_refund"`
	GmtClose            string `json:"gmt_close"`
	BuyerLogonID        string `json:"buyer_logon_id"`
	ChargeAmount        string `json:"charge_amount"`
	ChargeFlags         string `json:"charge_flags"`
	SettlementID        string `json:"settlement_id"`
	ReceiptCurrencyType string `json:"receipt_currency_type"`
	HybAmount           string `json:"hyb_amount"`
	EnterprisePayInfo   string `json:"enterprise_pay_info"`
}
