// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type EditArticleReq struct {
	Title    string `json:"title"`
	Content   string `json:"content"`
	Id int64 `json:"articleId"`
}

type EditArticleResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}
