// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type EditArticleReq struct {
	Id 		int  `json:"id,optional"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type EditArticleResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type ArticlePageReq struct {
	Page   int `form:"page"`
	Size   int `form:"size"`
}

type ArticleViewReq struct {
	Id    int64 `form:"id"`
	Published int64 `form:"published"`
}

