// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"codexie.com/w-book-user/internal/config"
	"codexie.com/w-book-user/internal/handler"
	"codexie.com/w-book-user/internal/logic"
	"codexie.com/w-book-user/internal/repo"
	"codexie.com/w-book-user/internal/repo/cache"
	"codexie.com/w-book-user/internal/repo/dao"
	"codexie.com/w-book-user/internal/svc"
	"github.com/google/wire"
	"github.com/zeromicro/go-zero/rest"
)

// Injectors from wire.go:

func NewApp(c config.Config) (*rest.Server, error) {
	db := svc.CreteDbClient(c)
	userDao := dao.NewUserDao(db)
	client := svc.CreateRedisClient(c)
	userCache := cache.NewRedisUserCache(client)
	iUserRepository := repo.NewUserRepository(userDao, userCache)
	codeClient := svc.CreateCodeRpcClient(c)
	iUserLogic := logic.NewUserLogic(c, iUserRepository, codeClient)
	userHandler := handler.NewUserHandler(iUserLogic)
	server := NewServer(c, userHandler, client)
	return server, nil
}

// wire.go:

var ServerSet = wire.NewSet(NewServer)

var HandlerSet = wire.NewSet(handler.NewUserHandler)

var LogicSet = wire.NewSet(logic.NewUserLogic)

var CtxSet = wire.NewSet(svc.NewServiceContext)

var DBSet = wire.NewSet(repo.NewUserRepository, dao.NewUserDao, cache.NewRedisUserCache)

var BaseSet = wire.NewSet(svc.CreteDbClient, svc.CreateRedisClient, svc.CreateCodeRpcClient)
