// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"codexie.com/w-book-account/internal/config"
	"codexie.com/w-book-account/internal/repo"
	"codexie.com/w-book-account/internal/service"
	"codexie.com/w-book-account/internal/svc"
	"codexie.com/w-book-common/ioc"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewAccountApp(config2 config.Config) (*App, error) {
	serviceContext := svc.NewServiceContext(config2)
	mySQLConf := config.GetMySQLConf(config2)
	db := InitDB(mySQLConf)
	accountRepo := repo.NewAccountRepository(db)
	accountService := service.NewAccountService(accountRepo)
	accountServer := InitRpcServer(serviceContext, accountService)
	app := &App{
		RpcServer: accountServer,
		SvcCtx:    serviceContext,
	}
	return app, nil
}

// wire.go:

var AppSet = wire.NewSet(InitRpcServer)

var LogicSet = wire.NewSet(service.NewAccountService)

var SvcSet = wire.NewSet(svc.NewServiceContext)

var DbSet = wire.NewSet(ioc.InitGormDB, ioc.InitRedis)

var ConfSet = wire.NewSet(config.GetMySQLConf)
