apiVersion: v1
kind: Service
metadata:
  name: w-book-user-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 20800
      nodePort: 30800  # 集群节点上的端口，范围 30000-32767
