receivers:
  # OpenTelemetry Protocol (OTLP) receiver (默认使用 HTTP 或 gRPC)
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14317
      http:
        endpoint: 0.0.0.0:14318
  skywalking:
    protocols:
      grpc:
        endpoint: 0.0.0.0:11800 # 接收 SkyWalking Agent 上报的 Trace 数据
      http:
        endpoint: 0.0.0.0:12800 # 接收从前端/ nginx 等 HTTP 协议上报的 Trace 数据      


processors:
  batch:
    # 批处理模式配置
    timeout: 2s          # 处理间隔时间
    send_batch_size: 1000  # 一次处理1000条数据

exporters:
  # File exporter 输出到 /data/trace/trace.json
  otlp:
    endpoint: 192.168.126.100:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp, skywalking]  # 接收来自 OTLP 和 SkyWalking 的数据
      processors: [batch]            # 使用批处理模式
      exporters: [otlp]              # 将数据导出到文件
