// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.1
// source: interact.proto

// proto 包名

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 查询交互计数请求
type QueryInteractionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Biz   string `protobuf:"bytes,1,opt,name=Biz,proto3" json:"Biz,omitempty"`      //业务类型
	BizId int64  `protobuf:"varint,2,opt,name=BizId,proto3" json:"BizId,omitempty"` //id
	Uid   int64  `protobuf:"varint,3,opt,name=Uid,proto3" json:"Uid,omitempty"`     //用户id
}

func (x *QueryInteractionReq) Reset() {
	*x = QueryInteractionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interact_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryInteractionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryInteractionReq) ProtoMessage() {}

func (x *QueryInteractionReq) ProtoReflect() protoreflect.Message {
	mi := &file_interact_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryInteractionReq.ProtoReflect.Descriptor instead.
func (*QueryInteractionReq) Descriptor() ([]byte, []int) {
	return file_interact_proto_rawDescGZIP(), []int{0}
}

func (x *QueryInteractionReq) GetBiz() string {
	if x != nil {
		return x.Biz
	}
	return ""
}

func (x *QueryInteractionReq) GetBizId() int64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *QueryInteractionReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type QueryInteractionsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Biz    string  `protobuf:"bytes,1,opt,name=Biz,proto3" json:"Biz,omitempty"`               //业务类型
	BizIds []int64 `protobuf:"varint,2,rep,packed,name=BizIds,proto3" json:"BizIds,omitempty"` //id
}

func (x *QueryInteractionsReq) Reset() {
	*x = QueryInteractionsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interact_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryInteractionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryInteractionsReq) ProtoMessage() {}

func (x *QueryInteractionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_interact_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryInteractionsReq.ProtoReflect.Descriptor instead.
func (*QueryInteractionsReq) Descriptor() ([]byte, []int) {
	return file_interact_proto_rawDescGZIP(), []int{1}
}

func (x *QueryInteractionsReq) GetBiz() string {
	if x != nil {
		return x.Biz
	}
	return ""
}

func (x *QueryInteractionsReq) GetBizIds() []int64 {
	if x != nil {
		return x.BizIds
	}
	return nil
}

// 增加阅读量请求
type AddReadCntReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Biz   string `protobuf:"bytes,1,opt,name=Biz,proto3" json:"Biz,omitempty"`      //业务类型
	BizId int64  `protobuf:"varint,2,opt,name=BizId,proto3" json:"BizId,omitempty"` //id
}

func (x *AddReadCntReq) Reset() {
	*x = AddReadCntReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interact_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReadCntReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReadCntReq) ProtoMessage() {}

func (x *AddReadCntReq) ProtoReflect() protoreflect.Message {
	mi := &file_interact_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReadCntReq.ProtoReflect.Descriptor instead.
func (*AddReadCntReq) Descriptor() ([]byte, []int) {
	return file_interact_proto_rawDescGZIP(), []int{2}
}

func (x *AddReadCntReq) GetBiz() string {
	if x != nil {
		return x.Biz
	}
	return ""
}

func (x *AddReadCntReq) GetBizId() int64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

type InteractionResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BizId       int64 `protobuf:"varint,1,opt,name=BizId,proto3" json:"BizId,omitempty"`
	ReadCnt     int64 `protobuf:"varint,2,opt,name=ReadCnt,proto3" json:"ReadCnt,omitempty"`
	CollectCnt  int64 `protobuf:"varint,3,opt,name=CollectCnt,proto3" json:"CollectCnt,omitempty"`
	LikeCnt     int64 `protobuf:"varint,4,opt,name=LikeCnt,proto3" json:"LikeCnt,omitempty"`
	IsLiked     bool  `protobuf:"varint,5,opt,name=IsLiked,proto3" json:"IsLiked,omitempty"`
	IsCollected bool  `protobuf:"varint,6,opt,name=IsCollected,proto3" json:"IsCollected,omitempty"`
}

func (x *InteractionResult) Reset() {
	*x = InteractionResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interact_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InteractionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionResult) ProtoMessage() {}

func (x *InteractionResult) ProtoReflect() protoreflect.Message {
	mi := &file_interact_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionResult.ProtoReflect.Descriptor instead.
func (*InteractionResult) Descriptor() ([]byte, []int) {
	return file_interact_proto_rawDescGZIP(), []int{3}
}

func (x *InteractionResult) GetBizId() int64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *InteractionResult) GetReadCnt() int64 {
	if x != nil {
		return x.ReadCnt
	}
	return 0
}

func (x *InteractionResult) GetCollectCnt() int64 {
	if x != nil {
		return x.CollectCnt
	}
	return 0
}

func (x *InteractionResult) GetLikeCnt() int64 {
	if x != nil {
		return x.LikeCnt
	}
	return 0
}

func (x *InteractionResult) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *InteractionResult) GetIsCollected() bool {
	if x != nil {
		return x.IsCollected
	}
	return false
}

type InteractionsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interactions []*InteractionResult `protobuf:"bytes,1,rep,name=interactions,proto3" json:"interactions,omitempty"` // InteractionResult 的列表
}

func (x *InteractionsInfo) Reset() {
	*x = InteractionsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interact_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InteractionsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionsInfo) ProtoMessage() {}

func (x *InteractionsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_interact_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionsInfo.ProtoReflect.Descriptor instead.
func (*InteractionsInfo) Descriptor() ([]byte, []int) {
	return file_interact_proto_rawDescGZIP(), []int{4}
}

func (x *InteractionsInfo) GetInteractions() []*InteractionResult {
	if x != nil {
		return x.Interactions
	}
	return nil
}

type TopLikeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []int64 `protobuf:"varint,1,rep,packed,name=Items,proto3" json:"Items,omitempty"`
}

func (x *TopLikeResp) Reset() {
	*x = TopLikeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interact_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopLikeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopLikeResp) ProtoMessage() {}

func (x *TopLikeResp) ProtoReflect() protoreflect.Message {
	mi := &file_interact_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopLikeResp.ProtoReflect.Descriptor instead.
func (*TopLikeResp) Descriptor() ([]byte, []int) {
	return file_interact_proto_rawDescGZIP(), []int{5}
}

func (x *TopLikeResp) GetItems() []int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

type TopLikeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Biz string `protobuf:"bytes,1,opt,name=Biz,proto3" json:"Biz,omitempty"` //业务类型
}

func (x *TopLikeReq) Reset() {
	*x = TopLikeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interact_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopLikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopLikeReq) ProtoMessage() {}

func (x *TopLikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_interact_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopLikeReq.ProtoReflect.Descriptor instead.
func (*TopLikeReq) Descriptor() ([]byte, []int) {
	return file_interact_proto_rawDescGZIP(), []int{6}
}

func (x *TopLikeReq) GetBiz() string {
	if x != nil {
		return x.Biz
	}
	return ""
}

type CommonResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *CommonResult) Reset() {
	*x = CommonResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interact_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResult) ProtoMessage() {}

func (x *CommonResult) ProtoReflect() protoreflect.Message {
	mi := &file_interact_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResult.ProtoReflect.Descriptor instead.
func (*CommonResult) Descriptor() ([]byte, []int) {
	return file_interact_proto_rawDescGZIP(), []int{7}
}

func (x *CommonResult) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PublishCommentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Biz      string `protobuf:"bytes,1,opt,name=Biz,proto3" json:"Biz,omitempty"`            //业务类型
	BizId    int64  `protobuf:"varint,2,opt,name=BizId,proto3" json:"BizId,omitempty"`       //id
	Content  string `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`    //内容
	ParentId int64  `protobuf:"varint,4,opt,name=ParentId,proto3" json:"ParentId,omitempty"` //父级id
}

func (x *PublishCommentReq) Reset() {
	*x = PublishCommentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interact_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCommentReq) ProtoMessage() {}

func (x *PublishCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_interact_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCommentReq.ProtoReflect.Descriptor instead.
func (*PublishCommentReq) Descriptor() ([]byte, []int) {
	return file_interact_proto_rawDescGZIP(), []int{8}
}

func (x *PublishCommentReq) GetBiz() string {
	if x != nil {
		return x.Biz
	}
	return ""
}

func (x *PublishCommentReq) GetBizId() int64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *PublishCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PublishCommentReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type CommentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Uid        int64  `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Content    string `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	CreateTime int64  `protobuf:"varint,4,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
}

func (x *CommentInfo) Reset() {
	*x = CommentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interact_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfo) ProtoMessage() {}

func (x *CommentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_interact_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfo.ProtoReflect.Descriptor instead.
func (*CommentInfo) Descriptor() ([]byte, []int) {
	return file_interact_proto_rawDescGZIP(), []int{9}
}

func (x *CommentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CommentInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type CommentListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Biz      string `protobuf:"bytes,1,opt,name=Biz,proto3" json:"Biz,omitempty"`            //业务类型
	BizId    int64  `protobuf:"varint,2,opt,name=BizId,proto3" json:"BizId,omitempty"`       //id
	Page     int64  `protobuf:"varint,3,opt,name=Page,proto3" json:"Page,omitempty"`         //页码
	PageSize int64  `protobuf:"varint,4,opt,name=PageSize,proto3" json:"PageSize,omitempty"` //每页条数
	LastSort int64  `protobuf:"varint,5,opt,name=LastSort,proto3" json:"LastSort,omitempty"` //最后一条评论热度
}

func (x *CommentListReq) Reset() {
	*x = CommentListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interact_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentListReq) ProtoMessage() {}

func (x *CommentListReq) ProtoReflect() protoreflect.Message {
	mi := &file_interact_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentListReq.ProtoReflect.Descriptor instead.
func (*CommentListReq) Descriptor() ([]byte, []int) {
	return file_interact_proto_rawDescGZIP(), []int{10}
}

func (x *CommentListReq) GetBiz() string {
	if x != nil {
		return x.Biz
	}
	return ""
}

func (x *CommentListReq) GetBizId() int64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *CommentListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CommentListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *CommentListReq) GetLastSort() int64 {
	if x != nil {
		return x.LastSort
	}
	return 0
}

type CommentListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comments []*CommentInfo `protobuf:"bytes,1,rep,name=Comments,proto3" json:"Comments,omitempty"`
}

func (x *CommentListResp) Reset() {
	*x = CommentListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interact_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentListResp) ProtoMessage() {}

func (x *CommentListResp) ProtoReflect() protoreflect.Message {
	mi := &file_interact_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentListResp.ProtoReflect.Descriptor instead.
func (*CommentListResp) Descriptor() ([]byte, []int) {
	return file_interact_proto_rawDescGZIP(), []int{11}
}

func (x *CommentListResp) GetComments() []*CommentInfo {
	if x != nil {
		return x.Comments
	}
	return nil
}

type LikeCommentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentId int64 `protobuf:"varint,3,opt,name=CommentId,proto3" json:"CommentId,omitempty"` //评论id
}

func (x *LikeCommentReq) Reset() {
	*x = LikeCommentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interact_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentReq) ProtoMessage() {}

func (x *LikeCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_interact_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentReq.ProtoReflect.Descriptor instead.
func (*LikeCommentReq) Descriptor() ([]byte, []int) {
	return file_interact_proto_rawDescGZIP(), []int{12}
}

func (x *LikeCommentReq) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type LikeCommentResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *LikeCommentResp) Reset() {
	*x = LikeCommentResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interact_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentResp) ProtoMessage() {}

func (x *LikeCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_interact_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentResp.ProtoReflect.Descriptor instead.
func (*LikeCommentResp) Descriptor() ([]byte, []int) {
	return file_interact_proto_rawDescGZIP(), []int{13}
}

func (x *LikeCommentResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_interact_proto protoreflect.FileDescriptor

var file_interact_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x4f, 0x0a, 0x13, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x42, 0x69, 0x7a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x42, 0x69, 0x7a, 0x12, 0x14,
	0x0a, 0x05, 0x42, 0x69, 0x7a, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x42,
	0x69, 0x7a, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x55, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x14, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x42, 0x69, 0x7a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x42, 0x69, 0x7a,
	0x12, 0x16, 0x0a, 0x06, 0x42, 0x69, 0x7a, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x06, 0x42, 0x69, 0x7a, 0x49, 0x64, 0x73, 0x22, 0x37, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x52,
	0x65, 0x61, 0x64, 0x43, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x42, 0x69, 0x7a,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x42, 0x69, 0x7a, 0x12, 0x14, 0x0a, 0x05, 0x42,
	0x69, 0x7a, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x42, 0x69, 0x7a, 0x49,
	0x64, 0x22, 0xb9, 0x01, 0x0a, 0x11, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x69, 0x7a, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x42, 0x69, 0x7a, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x52, 0x65, 0x61, 0x64, 0x43, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x43, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x43, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x69, 0x6b, 0x65, 0x43,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6e,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x49, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x49,
	0x73, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0b, 0x49, 0x73, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0x4e, 0x0a,
	0x10, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x3a, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x23, 0x0a,
	0x0b, 0x54, 0x6f, 0x70, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x22, 0x1e, 0x0a, 0x0a, 0x54, 0x6f, 0x70, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x42, 0x69, 0x7a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x42,
	0x69, 0x7a, 0x22, 0x20, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4d, 0x73, 0x67, 0x22, 0x71, 0x0a, 0x11, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x42, 0x69, 0x7a,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x42, 0x69, 0x7a, 0x12, 0x14, 0x0a, 0x05, 0x42,
	0x69, 0x7a, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x42, 0x69, 0x7a, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x69, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x42, 0x69, 0x7a, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x42, 0x69, 0x7a, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x69, 0x7a, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x42, 0x69, 0x7a, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x4c, 0x61, 0x73, 0x74, 0x53, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x4c, 0x61, 0x73, 0x74, 0x53, 0x6f, 0x72, 0x74, 0x22, 0x3f, 0x0a, 0x0f, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x08,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x2e, 0x0a, 0x0e, 0x4c, 0x69,
	0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x23, 0x0a, 0x0f, 0x4c, 0x69,
	0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x32,
	0xba, 0x03, 0x0a, 0x0b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x48, 0x0a, 0x14, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x49, 0x0a, 0x15, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x0c, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x52, 0x65, 0x61,
	0x64, 0x43, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x61, 0x64, 0x43, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x54,
	0x6f, 0x70, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x6f, 0x70,
	0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x6f,
	0x70, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x0e, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x38, 0x0a, 0x0b, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x6b,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x08, 0x5a, 0x06,
	0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_interact_proto_rawDescOnce sync.Once
	file_interact_proto_rawDescData = file_interact_proto_rawDesc
)

func file_interact_proto_rawDescGZIP() []byte {
	file_interact_proto_rawDescOnce.Do(func() {
		file_interact_proto_rawDescData = protoimpl.X.CompressGZIP(file_interact_proto_rawDescData)
	})
	return file_interact_proto_rawDescData
}

var file_interact_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_interact_proto_goTypes = []any{
	(*QueryInteractionReq)(nil),  // 0: api.QueryInteractionReq
	(*QueryInteractionsReq)(nil), // 1: api.QueryInteractionsReq
	(*AddReadCntReq)(nil),        // 2: api.AddReadCntReq
	(*InteractionResult)(nil),    // 3: api.InteractionResult
	(*InteractionsInfo)(nil),     // 4: api.InteractionsInfo
	(*TopLikeResp)(nil),          // 5: api.TopLikeResp
	(*TopLikeReq)(nil),           // 6: api.TopLikeReq
	(*CommonResult)(nil),         // 7: api.CommonResult
	(*PublishCommentReq)(nil),    // 8: api.PublishCommentReq
	(*CommentInfo)(nil),          // 9: api.CommentInfo
	(*CommentListReq)(nil),       // 10: api.CommentListReq
	(*CommentListResp)(nil),      // 11: api.CommentListResp
	(*LikeCommentReq)(nil),       // 12: api.LikeCommentReq
	(*LikeCommentResp)(nil),      // 13: api.LikeCommentResp
}
var file_interact_proto_depIdxs = []int32{
	3,  // 0: api.InteractionsInfo.interactions:type_name -> api.InteractionResult
	9,  // 1: api.CommentListResp.Comments:type_name -> api.CommentInfo
	0,  // 2: api.Interaction.QueryInteractionInfo:input_type -> api.QueryInteractionReq
	1,  // 3: api.Interaction.QueryInteractionsInfo:input_type -> api.QueryInteractionsReq
	2,  // 4: api.Interaction.IncreReadCnt:input_type -> api.AddReadCntReq
	6,  // 5: api.Interaction.TopLike:input_type -> api.TopLikeReq
	8,  // 6: api.Interaction.PublishComment:input_type -> api.PublishCommentReq
	10, // 7: api.Interaction.GetCommentList:input_type -> api.CommentListReq
	12, // 8: api.Interaction.LikeComment:input_type -> api.LikeCommentReq
	3,  // 9: api.Interaction.QueryInteractionInfo:output_type -> api.InteractionResult
	4,  // 10: api.Interaction.QueryInteractionsInfo:output_type -> api.InteractionsInfo
	7,  // 11: api.Interaction.IncreReadCnt:output_type -> api.CommonResult
	5,  // 12: api.Interaction.TopLike:output_type -> api.TopLikeResp
	9,  // 13: api.Interaction.PublishComment:output_type -> api.CommentInfo
	11, // 14: api.Interaction.GetCommentList:output_type -> api.CommentListResp
	13, // 15: api.Interaction.LikeComment:output_type -> api.LikeCommentResp
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_interact_proto_init() }
func file_interact_proto_init() {
	if File_interact_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_interact_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*QueryInteractionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interact_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*QueryInteractionsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interact_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AddReadCntReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interact_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*InteractionResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interact_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*InteractionsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interact_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*TopLikeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interact_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*TopLikeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interact_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CommonResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interact_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*PublishCommentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interact_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*CommentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interact_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*CommentListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interact_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*CommentListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interact_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*LikeCommentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interact_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*LikeCommentResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_interact_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interact_proto_goTypes,
		DependencyIndexes: file_interact_proto_depIdxs,
		MessageInfos:      file_interact_proto_msgTypes,
	}.Build()
	File_interact_proto = out.File
	file_interact_proto_rawDesc = nil
	file_interact_proto_goTypes = nil
	file_interact_proto_depIdxs = nil
}
