// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"testing"

	"codexie.com/w-book-article/internal/config"
	"codexie.com/w-book-article/internal/dao/cache"
	"codexie.com/w-book-article/internal/dao/db"
	"codexie.com/w-book-article/internal/handler"
	"codexie.com/w-book-article/internal/logic"
	"codexie.com/w-book-article/internal/repo"
	"codexie.com/w-book-article/internal/svc"
	"codexie.com/w-book-common/kafka/producer"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewApp(c config.Config, t *testing.T) (*App, error) {
	serviceContext := svc.NewServiceContext(c)
	gormDB := InitGormDB()
	authorDao := db.NewAuthorDao(gormDB)
	client := InitRedis()
	articleCache := cache.NewArticleRedis(client)
	iAuthorRepository := repo.NewAuthorRepository(authorDao, articleCache)
	readerDao := db.NewReaderDao(gormDB)
	iReaderRepository := repo.NewReaderRepository(readerDao, articleCache)
	interactionClient := InitInteractClient(t)
	saramaClient := InitKafkaClient()
	producerProducer := producer.NewKafkaProducer(saramaClient)
	articleLogic := logic.NewArticleLogic(iAuthorRepository, iReaderRepository, interactionClient, producerProducer)
	localArtTopCache := cache.NewLocalArtTopCache()
	redisArtTopNCache := cache.NewRankCacheRedis(client)
	rankRepo := repo.NewRankRepo(localArtTopCache, redisArtTopNCache)
	redsync := InitRedLock()
	rankingLogic := logic.NewRankingLogic(iReaderRepository, rankRepo, redsync, interactionClient)
	articleHandler := handler.NewArticleHandler(serviceContext, articleLogic, rankingLogic)
	app := NewArticleApp(c, articleHandler, client)
	return app, nil
}

// wire.go:

var AppSet = wire.NewSet(NewArticleApp)

var HandlerSet = wire.NewSet(handler.NewArticleHandler)

var LogicSet = wire.NewSet(logic.NewArticleLogic, logic.NewRankingLogic)

var SvcSet = wire.NewSet(svc.NewServiceContext)

var RepoSet = wire.NewSet(repo.NewAuthorRepository, repo.NewReaderRepository, repo.NewRankRepo)

var DaoSet = wire.NewSet(db.NewAuthorDao, db.NewReaderDao)

var CacheSet = wire.NewSet(cache.NewRankCacheRedis, cache.NewLocalArtTopCache, cache.NewArticleRedis)

var DbSet = wire.NewSet(InitGormDB, InitRedis, InitRedLock)

var MessageSet = wire.NewSet(InitKafkaClient, producer.NewKafkaProducer)

var RpcSet = wire.NewSet(svc.CreateCodeRpcClient)
